import icedtea-web-1.6.2

diff --git a/Makefile.in b/Makefile.in
--- a/Makefile.in
+++ b/Makefile.in
@@ -858,7 +858,7 @@ export NETX_PKGS = javax.jnlp net.sourceforge.nanoxml net.sourceforge.jnlp \
 export PLUGIN_VERSION = IcedTea-Web $(FULL_VERSION)
 
 export EXTRA_DIST = $(top_srcdir)/netx $(top_srcdir)/plugin javaws.png javaws.desktop.in policyeditor.desktop.in icedteaweb-completion \
- itweb-settings.desktop.in launcher $(top_srcdir)/tests html-gen.sh NEW_LINE_IFS
+ itweb-settings.desktop.in launcher $(top_srcdir)/tests html-gen.sh NEW_LINE_IFS $(top_srcdir)/metadata.in
 
 # reproducers `D`shortcuts
 export DTEST_SERVER=-Dtest.server.dir=$(REPRODUCERS_TESTS_SERVER_DEPLOYDIR)
@@ -884,7 +884,7 @@ all-local: stamps/netx-dist.stamp stamps/plugin.stamp launcher.build/$(javaws) \
 check-local: $(RHINO_TESTS) $(JUNIT_TESTS)
 
 clean-local: clean-netx clean-plugin clean-liveconnect \
- clean-native-ecj clean-launchers clean-desktop-files clean-docs clean-generated-docs clean-tests clean-bootstrap-directory
+ clean-native-ecj clean-launchers clean-desktop-files clean-docs clean-generated-docs clean-metadata clean-tests clean-bootstrap-directory
 	if [ -e stamps ] ; then \
 	  rmdir stamps ; \
 	fi
@@ -892,7 +892,7 @@ clean-local: clean-netx clean-plugin clean-liveconnect \
 .PHONY: clean-IcedTeaPlugin clean-add-netx clean-add-netx-debug clean-add-plugin clean-add-plugin-debug \
  clean-bootstrap-directory clean-native-ecj clean-desktop-files clean-netx-docs clean-docs clean-plugin-docs clean-generated-docs \
  clean-tests check-local clean-launchers stamps/check-pac-functions.stamp stamps/run-netx-unit-tests.stamp clean-netx-tests \
- clean-junit-runner clean-netx-unit-tests
+ clean-junit-runner clean-netx-unit-tests clean-metadata 
 
 install-exec-local:
 	${mkinstalldirs} $(DESTDIR)$(bindir) $(DESTDIR)$(datadir)/$(PACKAGE_NAME)/ $(DESTDIR)$(libdir) $(ICONS_DEST_DIR)
@@ -1104,6 +1104,47 @@ netx-source-files.txt:
 	done
 @WITH_RHINO_FALSE@	sed -i '/RhinoBasedPacEvaluator/ d' $@
 
+# if 'sed' will be missing on machine, use old IFS hack as on other places
+# the 'sed' cycles is changing some custom version like 1.6.2 fedora23.4 to simple 1.6
+# if changed, keep in mind that also 1.7 should bubble to 1.7
+# also 1.7pre or 1.7preHASH should end up like 1.7
+$(abs_top_builddir)/metadata: $(top_srcdir)/metadata.in
+	mkdir -p $(abs_top_builddir)/metadata-work ; \
+	METAFILES=`ls $(top_srcdir)/metadata.in` ; \
+	SEDDED_VERSION=`echo "$(FULL_VERSION)" | sed 's/[^0-9]\+/ /g'` ; \
+	x=0; for i in $$SEDDED_VERSION ; do  \
+	  let x++; \
+	  if [ $$x -eq 1 ] ; then V1=$$i; fi; \
+	  if [ $$x -eq 2 ] ; then V2=$$i; fi; \
+	done; \
+	XVERSION=$$V1.$$V2; \
+	for F in $$METAFILES ; do \
+	  cat $(top_srcdir)/metadata.in/$$F | sed "s;%{name};$(PACKAGE_NAME);g" |  sed "s;%{version};$$XVERSION;g" > $(abs_top_builddir)/metadata-work/$$F ; \
+	done ; \
+	mv $(abs_top_builddir)/metadata-work $(abs_top_builddir)/metadata ;
+
+check-metadata: $(abs_top_builddir)/metadata
+	xmllint --noout $(abs_top_builddir)/metadata/* ; \
+	if [ $$? -eq 0 ] ; then \
+	  echo "Passed: well formed" ; \
+	else \
+	  echo "FAILED: well formed" ; \
+	fi ; \
+	xmllint --noout --schema http://maven.apache.org/xsd/maven-4.0.0.xsd $(abs_top_builddir)/metadata/*.pom ; \
+	if [ $$? -eq 0 ] ; then \
+	  echo "Passed: valid poms" ; \
+	else \
+	  echo "FAILED: valid poms" ; \
+	fi ; \
+	appstream-util validate $(abs_top_builddir)/metadata/*.appdata.xml  $(abs_top_builddir)/metadata/*.metainfo.xml ; \
+	if [ $$? -eq 0 ] ; then \
+	  echo "Passed: valid software descriptors" ; \
+	else \
+	  echo "FAILED: valid software descriptors" ; \
+	fi ;
+# very strange results:
+# appstreamcli  validate $(abs_top_builddir)/metadata/*.appdata.xml  $(abs_top_builddir)/metadata/*.metainfo.xml
+
 stamps/generate-docs.stamp: stamps/netx.stamp
 	mkdir -p "$(DOCS_DIR)" ; \
 	HTML_DOCS_TARGET_DIR="$(DOCS_DIR)/html"  ; \
@@ -1117,7 +1158,7 @@ stamps/generate-docs.stamp: stamps/netx.stamp
 	TP_TAIL="false $(FULL_VERSION)" ; \
 	LANG_BACKUP=$$LANG ; \
 	echo "<html><head><title>$(PLUGIN_VERSION)</title></head>" > "$$HTML_DOCS_INDEX" ; \
-	echo "<body><h3>$(PLUGIN_VERSION) docs:</h3>"  >> $$HTML_DOCS_INDEX ; \
+	echo "<body><h3>$(PLUGIN_VERSION) docs:</h3>"  >> "$$HTML_DOCS_INDEX" ; \
 	for LANG_ID in en_US.UTF-8 cs_CZ.UTF-8 pl_PL.UTF-8 de_DE.UTF-8 ;  do \
 	  ID=`echo "$$LANG_ID" | head -c 2` ; \
 	  ENCOD=`echo "$$LANG_ID" | tail -c 6 -` ; \
@@ -1127,7 +1168,7 @@ stamps/generate-docs.stamp: stamps/netx.stamp
 	  $$TP_COMMAND html "$$HTML_DOCS_TARGET_DIR/$$ID" $$TP_TAIL ; \
 	  mkdir "$$PLAIN_DOCS_TARGET_DIR/$$ID" ; \
 	  $$TP_COMMAND plain "$$PLAIN_DOCS_TARGET_DIR/$$ID" 160 $$TP_TAIL; \
-	  if [ $$ID == "en" ] ; then \
+	  if [ $$ID = "en" ] ; then \
 	    MAN_DESC="$$MAN_DOCS_TARGET_DIR/man1" ; \
 	  else \
 	    MAN_DESC="$$MAN_DOCS_TARGET_DIR/$$ID/man1" ; \
@@ -1145,7 +1186,7 @@ stamps/netx-html-gen.stamp:
 	mkdir -p html-gen; \
 	cp AUTHORS NEWS COPYING ChangeLog html-gen/; \
 	export HTML_GEN_DEBUG=true; \
-	bash html-gen.sh 40; \
+	${SHELL} html-gen.sh 33; \
 	unset HTML_GEN_DEBUG)
 	${INSTALL_DATA} $(NETX_SRCDIR)/../html-gen/*.html $(NETX_RESOURCE_DIR)
 	rm -r $(NETX_SRCDIR)/../html-gen/
@@ -1171,7 +1212,7 @@ stamps/netx.stamp: netx-source-files.txt stamps/netx-html-gen.stamp
 	mkdir -p stamps
 	touch $@
 
-stamps/netx-dist.stamp: stamps/netx.stamp $(abs_top_builddir)/netx.manifest stamps/generate-docs.stamp
+stamps/netx-dist.stamp: stamps/netx.stamp $(abs_top_builddir)/netx.manifest stamps/generate-docs.stamp $(abs_top_builddir)/metadata
 	(cd $(NETX_DIR) ; \
 	 mkdir -p lib ; \
 	 $(SYSTEM_JDK_DIR)/bin/jar cfm lib/classes.jar \
@@ -1247,7 +1288,7 @@ clean-docs: clean-netx-docs clean-plugin-docs
 	rm -f stamps/docs.stamp
 
 stamps/netx-docs.stamp:
-@ENABLE_DOCS_TRUE@	$(SYSTEM_JDK_DIR)/bin/javadoc $(JAVADOC_MEM_OPTS) $(	_OPTS) \
+@ENABLE_DOCS_TRUE@	$(SYSTEM_JDK_DIR)/bin/javadoc $(JAVADOC_MEM_OPTS) $(JAVADOC_OPTS) \
 @ENABLE_DOCS_TRUE@	 -d ${abs_top_builddir}/docs/netx -sourcepath $(NETX_SRCDIR) \
 @ENABLE_DOCS_TRUE@	 -doctitle 'IcedTea-Web: NetX API Specification' \
 @ENABLE_DOCS_TRUE@	 -windowtitle 'IcedTea-Web: NetX ' \
@@ -1279,6 +1320,9 @@ clean-plugin-docs:
 clean-generated-docs:
 	rm -rf "$(DOCS_DIR)"
 	rm -f stamps/generate-docs.stamp
+
+clean-metadata:
+	rm -rf $(abs_top_builddir)/metadata
 
 # check
 # ==========================
